# Copyright SecurDrgorP. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

################################################################################
#   Organizations Section
################################################################################
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: organizations/ordererOrganizations/example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
        OrdererEndpoints:
            - orderer.example.com:7050
            - orderer2.example.com:7052
            - orderer3.example.com:7054

    - &ParkingOperator
        Name: ParkingOperatorMSP
        ID: ParkingOperatorMSP
        MSPDir: organizations/peerOrganizations/org1.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ParkingOperatorMSP.admin', 'ParkingOperatorMSP.peer', 'ParkingOperatorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ParkingOperatorMSP.admin', 'ParkingOperatorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ParkingOperatorMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ParkingOperatorMSP.peer')"
        AnchorPeers:
            - Host: peer0.org1.example.com
              Port: 7051

    - &ChargingStation
        Name: ChargingStationMSP
        ID: ChargingStationMSP
        MSPDir: organizations/peerOrganizations/org2.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ChargingStationMSP.admin', 'ChargingStationMSP.peer', 'ChargingStationMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ChargingStationMSP.admin', 'ChargingStationMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ChargingStationMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ChargingStationMSP.peer')"
        AnchorPeers:
            - Host: peer0.org2.example.com
              Port: 9051

    - &UserService
        Name: UserServiceMSP
        ID: UserServiceMSP
        MSPDir: organizations/peerOrganizations/org3.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('UserServiceMSP.admin', 'UserServiceMSP.peer', 'UserServiceMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('UserServiceMSP.admin', 'UserServiceMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('UserServiceMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('UserServiceMSP.peer')"
        AnchorPeers:
            - Host: peer0.org3.example.com
              Port: 11051

################################################################################
#   Capabilities Section
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_5: true

################################################################################
#   Application Section
################################################################################
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   Orderer Section
################################################################################
Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:
        - orderer.example.com:7050
        - orderer2.example.com:7052
        - orderer3.example.com:7054
    EtcdRaft:
        Consenters:
            - Host: orderer.example.com
              Port: 7050
              ClientTLSCert: organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
              ServerTLSCert: organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
            - Host: orderer2.example.com
              Port: 7052
              ClientTLSCert: organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.crt
              ServerTLSCert: organizations/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.crt
            - Host: orderer3.example.com
              Port: 7054
              ClientTLSCert: organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt
              ServerTLSCert: organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Channel Section
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Profiles Section
################################################################################
Profiles:
    ThreeOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            CityFlowConsortium:
                Organizations:
                    - *ParkingOperator
                    - *ChargingStation
                    - *UserService

    UserChannel:
        Consortium: CityFlowConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ParkingOperator
                - *ChargingStation
                - *UserService

    ParkingChannel:
        Consortium: CityFlowConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ParkingOperator
                - *ChargingStation
                - *UserService

    ChargingChannel:
        Consortium: CityFlowConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ParkingOperator
                - *ChargingStation
                - *UserService

    WalletChannel:
        Consortium: CityFlowConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ParkingOperator
                - *ChargingStation
                - *UserService
