# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# CityFlow Parking - Channel Configuration

################################################################################
#   Organizations Section
################################################################################
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/cityflow.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.cityflow.com:7050

  - &ParkingOperator
    Name: ParkingOperatorMSP
    ID: ParkingOperatorMSP
    MSPDir: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/parkingoperator.cityflow.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ParkingOperatorMSP.admin', 'ParkingOperatorMSP.peer', 'ParkingOperatorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ParkingOperatorMSP.admin', 'ParkingOperatorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ParkingOperatorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ParkingOperatorMSP.peer')"
    AnchorPeers:
      - Host: peer0.parkingoperator.cityflow.com
        Port: 7051

  - &ChargingStation
    Name: ChargingStationMSP
    ID: ChargingStationMSP
    MSPDir: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/chargingstation.cityflow.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ChargingStationMSP.admin', 'ChargingStationMSP.peer', 'ChargingStationMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ChargingStationMSP.admin', 'ChargingStationMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ChargingStationMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ChargingStationMSP.peer')"
    AnchorPeers:
      - Host: peer0.chargingstation.cityflow.com
        Port: 8051

  - &UserService
    Name: UserServiceMSP
    ID: UserServiceMSP
    MSPDir: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/userservice.cityflow.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('UserServiceMSP.admin', 'UserServiceMSP.peer', 'UserServiceMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('UserServiceMSP.admin', 'UserServiceMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('UserServiceMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('UserServiceMSP.peer')"
    AnchorPeers:
      - Host: peer0.userservice.cityflow.com
        Port: 9051

  - &CityManagement
    Name: CityManagementMSP
    ID: CityManagementMSP
    MSPDir: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/citymanagement.cityflow.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('CityManagementMSP.admin', 'CityManagementMSP.peer', 'CityManagementMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('CityManagementMSP.admin', 'CityManagementMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('CityManagementMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('CityManagementMSP.peer')"
    AnchorPeers:
      - Host: peer0.citymanagement.cityflow.com
        Port: 10051

################################################################################
#   Capabilities Section
################################################################################
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

################################################################################
#   Application Section
################################################################################
Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

################################################################################
#   Orderer Section
################################################################################
Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.cityflow.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.cityflow.com
        Port: 7050
        ClientTLSCert: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/cityflow.com/orderers/orderer.cityflow.com/tls/server.crt
        ServerTLSCert: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/cityflow.com/orderers/orderer.cityflow.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

################################################################################
#   Channel Section
################################################################################
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

################################################################################
#   Profiles Section
################################################################################
Profiles:
  CityFlowGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *ParkingOperator
        - *ChargingStation
        - *UserService
        - *CityManagement
      Capabilities:
        <<: *ApplicationCapabilities

  # User Channel Profile
  UserChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *UserService
        - *ParkingOperator
        - *ChargingStation
      Capabilities:
        <<: *ApplicationCapabilities

  # Parking Channel Profile
  ParkingChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *ParkingOperator
        - *UserService
        - *CityManagement
      Capabilities:
        <<: *ApplicationCapabilities

  # Charging Channel Profile
  ChargingChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *ChargingStation
        - *UserService
        - *CityManagement
      Capabilities:
        <<: *ApplicationCapabilities

  # Wallet Channel Profile
  WalletChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *UserService
        - *ParkingOperator
        - *ChargingStation
        - *CityManagement
      Capabilities:
        <<: *ApplicationCapabilities
